#!/bin/bash
# Wrapper which allows Freevo to use the iplayer plugin to play streams from iplayer site
#
# Author: Phil Lewis
#
# * Still needs lots of improving
#
# Install iplayer.py in Freevo plugins directory
# Activate the plugin in the freevo local_conf.py:
#   plugin.activate('iplayer.fxdhandler');
# Point video items to the FXD file created by get_iplayer in local_conf.py:
# e.g:
#   VIDEO_ITEMS = [ '/home/plewis/iplayer_downloads/folder.fxd', <other items>, ]
# Run get_iplayer to generate the FXD file
# Restart Freevo
#
/home/plewis/get_iplayer -o /home/plewis/iplayer -x $1 | /usr/bin/mplayer -fs -cache 2048 - &
#/home/plewis/get_iplayer -o /home/plewis/iplayer -x $1 | /usr/bin/xine -f -g --no-splash stdin:/ &
PID=$!
# Loop to kill off parent streaming when player is killed
while [ 1 == 1 ]; do
        sleep 2
        # player still alive?
        kill -0 $PID  >/dev/null  2>&1
        # Commit suicide if player is dead
        if [ $? != 0 ]; then
          killall -9 get_iplayer >/dev/null 2>&1
          kill -9 $$ >/dev/null 2>&1
        fi
done

