.TH GET_IPLAYER "1" "February 2019" "Phil Lewis" "get_iplayer Manual"
.SH NAME
get_iplayer \- Stream Recording tool and PVR for BBC iPlayer
.SH SYNOPSIS
\fBget_iplayer\fR [<options>] [<regex|index> ...]
.PP
\fBget_iplayer\fR \fB\-\-get\fR [<options>] <regex|index> ...
.PP
\fBget_iplayer\fR <url> [\fB\-\-type\fR=<type> <options>]
.PP
\fBget_iplayer\fR <pid> [\fB\-\-type\fR=<type> <options>]
.PP
\fBget_iplayer\fR \fB\-\-refresh\fR [\fB\-\-type\fR=<type> <options>]
.SH DESCRIPTION
\fBget_iplayer\fR lists, searches and records BBC iPlayer TV and radio programmes.
.PP
\fBget_iplayer\fR has two modes: recording a complete programme for later playback, and as a Personal Video Recorder (PVR), subscribing to
search terms and recording programmes automatically.
.PP
If given the regex ".*" (incl. quotes), \fBget_iplayer\fR updates and displays the list of currently available TV programmes.
Use \-\-type=radio for radio programmes. Each available programme has an alphanumeric identifier (\fBPID\fR).
.PP
In PVR mode, \fBget_iplayer\fR can be called from cron to record programmes on a schedule.
.SH "OPTIONS"
.PP
Boolean options can be negated by adding a "no\-" prefix, e.g., \-\-no\-subtitles or \-\-no\-whitespace.
This applies even if the base option name already begins with "no\-", e.g., \-\-no\-no\-tag or \-\-no\-no\-artwork
.SS "Search Options:"
.TP
\fB\-\-available\-before <hours>
Limit search to programmes that became available before <hours> hours ago
.TP
\fB\-\-available\-since <hours>
Limit search to programmes that have become available in the last <hours> hours
.TP
\fB\-\-before <hours>
Limit search to programmes added to the cache before <hours> hours ago
.TP
\fB\-\-category <string>
Narrow search to matched categories (comma\-separated regex list).  Defaults to substring match.  Only works with \-\-history.
.TP
\fB\-\-channel <string>
Narrow search to matched channel(s) (comma\-separated regex list).  Defaults to substring match.
.TP
\fB\-\-exclude <string>
Narrow search to exclude matched programme names (comma\-separated regex list).  Defaults to substring match.
.TP
\fB\-\-exclude\-category <string>
Narrow search to exclude matched categories (comma\-separated regex list).  Defaults to substring match.  Only works with \-\-history.
.TP
\fB\-\-exclude\-channel <string>
Narrow search to exclude matched channel(s) (comma\-separated regex list).  Defaults to substring match.
.TP
\fB\-\-expires\-after <hours>
Limit search to programmes that will expire after <hours> hours from now
.TP
\fB\-\-expires\-before <hours>
Limit search to programmes that will expire before <hours> hours from now
.TP
\fB\-\-fields <field1>,<field2>,...
Searches only in the specified fields. The fields are concatenated with spaces in the order specified and the search term is applied to the resulting string.
.TP
\fB\-\-future
Additionally search future programme schedule if it has been indexed (refresh cache with: \-\-refresh \-\-refresh\-future).
.TP
\fB\-\-history
Search recordings history (requires search term)
.TP
\fB\-\-long, \-l
Additionally search in programme descriptions and episode names (same as \-\-fields=name,episode,desc )
.TP
\fB\-\-search <search term>
GetOpt compliant way of specifying search args
.TP
\fB\-\-since <hours>
Limit search to programmes added to the cache in the last <hours> hours
.TP
\fB\-\-type <type>,<type>,...
Only search in these types of programmes: tv,radio,all (tv is default)
.SS "Display Options:"
.TP
\fB\-\-conditions
Shows GPLv3 conditions
.TP
\fB\-\-debug
Debug output (very verbose and rarely useful)
.TP
\fB\-\-dump\-options
Dumps all options with their internal option key names
.TP
\fB\-\-help, \-h
Intermediate help text
.TP
\fB\-\-helpbasic, \-\-usage
Basic help text
.TP
\fB\-\-helplong
Advanced help text
.TP
\fB\-\-hide
Hide previously recorded programmes
.TP
\fB\-\-info, \-i
Show full programme metadata and availability of modes and subtitles (max 40 matches)
.TP
\fB\-\-list <element>
Show a list of distinct element values (with counts) for the selected programme type(s) and exit.  Valid elements are: 'channel'
.TP
\fB\-\-listformat <format>
Display search results with a custom format. Use substitution parameters in format string (see docs for list).
.TP
\fB\-\-long, \-l
Show extended programme info
.TP
\fB\-\-manpage <file>
Create man page based on current help text
.TP
\fB\-\-nocopyright
Don't display copyright header
.TP
\fB\-\-page <number>
Page number to display for multipage output
.TP
\fB\-\-pagesize <number>
Number of matches displayed on a page for multipage output
.TP
\fB\-\-quiet, \-q
Reduce logging output
.TP
\fB\-\-series
Display programme series names only with number of episodes
.TP
\fB\-\-show\-cache\-age
Display the age of the selected programme caches then exit
.TP
\fB\-\-show\-options
Show options which are set and where they are defined
.TP
\fB\-\-silent
No logging output except PVR download report.  Cannot be saved in preferences or PVR searches.
.TP
\fB\-\-sort <fieldname>
Field to use to sort displayed matches
.TP
\fB\-\-sortreverse
Reverse order of sorted matches
.TP
\fB\-\-streaminfo
Returns all of the media stream URLs of the programme(s)
.TP
\fB\-\-terse
Only show terse programme info (does not affect searching)
.TP
\fB\-\-tree
Display programme listings in a tree view
.TP
\fB\-\-verbose, \-v
Show additional output (useful for diagnosing problems)
.TP
\fB\-\-warranty
Displays warranty section of GPLv3
.TP
\fB\-V
Show get_iplayer version and exit.
.SS "Recording Options:"
.TP
\fB\-\-attempts <number>
Number of attempts to make or resume a failed connection.  \-\-attempts is applied per\-stream, per\-mode.  Many modes have two or more streams available.
.TP
\fB\-\-audio\-only
Only download audio stream for TV programme. 'hls' recording modes are not supported and ignored. Produces .m4a file. Implies \-\-force.
.TP
\fB\-\-download\-abortonfail
Exit immediately if stream for any recording mode fails to download. Use to avoid repeated failed download attempts if connection is dropped or access is blocked.
.TP
\fB\-\-exclude\-supplier <supplier>,<supplier>,...
Comma\-separated list of media stream suppliers to skip.  Possible values: akamai,limelight,bidi
.TP
\fB\-\-force
Ignore programme history (unsets \-\-hide option also).
.TP
\fB\-\-fps25
Use only 25fps streams for TV programmes (HD video not available).
.TP
\fB\-\-get, \-g
Start recording matching programmes. Search terms required.
.TP
\fB\-\-hash
Show recording progress as hashes
.TP
\fB\-\-hls\-lq\-audio
Use default lower\-quality audio for 'hvf' modes (TV only). Instead of 320k audio, output file will contain 128k or 96k audio, depending on the stream downloaded.
.TP
\fB\-\-include\-supplier <supplier>,<supplier>,...
Comma\-separated list of media stream suppliers to use if not included by default.  Possible values: akamai,limelight,bidi
.TP
\fB\-\-log\-progress
Force HLS/DASH download progress display to be captured when screen output is redirected to file.  Progress display is normally omitted unless writing to terminal.
.TP
\fB\-\-mark\-downloaded
Mark programmes in search results or specified with \-\-pid/\-\-url as downloaded by inserting records in download history.
.TP
\fB\-\-modes <mode>,<mode>,...
Recording modes.  See \-\-tvmode and \-\-radiomode (with \-\-long\-help) for available modes and defaults.  Shortcuts: tvbest,tvbetter,tvgood,tvworst,radiobest,radiobetter,radiogood,radioworst (default=default for programme type).
.TP
\fB\-\-no\-merge\-versions
Do not merge programme versions with same name and duration.
.TP
\fB\-\-no\-proxy
Ignore \-\-proxy setting in preferences and/or http_proxy environment variable.
.TP
\fB\-\-no\-resume
Do not resume partial HLS/DASH downloads.
.TP
\fB\-\-no\-verify
Do not verify size of downloaded HLS/DASH file segments or file resize upon resume.
.TP
\fB\-\-overwrite
Overwrite recordings if they already exist
.TP
\fB\-\-partial\-proxy
Only uses web proxy where absolutely required (try this extra option if your proxy fails).
.TP
\fB\-\-pid <pid>,<pid>,...
Record arbitrary PIDs that do not necessarily appear in the index.
.TP
\fB\-\-pid\-index
Update (if necessary) and use programme index cache with \-\-pid. Cache is not searched for programme by default with \-\-pid. Synonym: \-\-pid\-refresh.
.TP
\fB\-\-pid\-recursive
Record all related episodes if value of \-\-pid is a series or brand PID.  Requires \-\-pid.
.TP
\fB\-\-pid\-recursive\-list
If value of \-\-pid is a series or brand PID, list available episodes but do not download. Implies \-\-pid\-recursive. Requires \-\-pid.
.TP
\fB\-\-proxy, \-p <url>
Web proxy URL, e.g., http://username:password@server:port or http://server:port.  Value of http_proxy environment variable (if present) will be used unless \-\-proxy is specified. Used for both HTTP and HTTPS. Overridden by \-\-no\-proxy.
.TP
\fB\-\-radiomode <mode>,<mode>,...
Radio recording modes (overrides \-\-modes): dafhigh,dafstd,dafmed,daflow,hafhigh,hafstd,hafmed,haflow,hlahigh,hlastd,hlsmed,hlalow. Shortcuts: best,better,good,worst,haf,hla,daf,hls,dash,high,std,med,low (default=hafhigh,hlahigh,dafhigh,hafstd,hlastd,dafstd,hafmed,hlamed,dafmed,haflow,hlalow,daflow).
.TP
\fB\-\-start <secs|hh:mm:ss>
Recording/streaming start offset (actual start may be several seconds earlier for HLS and DASH streams)
.TP
\fB\-\-stop <secs|hh:mm:ss>
Recording/streaming stop offset (actual stop may be several seconds later for HLS and DASH streams)
.TP
\fB\-\-subtitles\-required
Do not download TV programme if subtitles are not available.
.TP
\fB\-\-test, \-t
Test only \- no recording (only shows search results with \-\-pvr and \-\-pid\-recursive)
.TP
\fB\-\-tvmode <mode>,<mode>,...
TV recording modes (overrides \-\-modes): dvfhd,dvfsd,dvfxsd,dvfhigh,dvfxhigh,dvflow,hlshd,hvfhd,hvfsd,hvfxsd,hvfhigh,hvfxhigh,hvflow. Shortcuts: best,better,good,worst,dvf,hvf,dash,hls,hd,sd,high,low. 50fps streams (if available) preferred unless \-\-fps25 specified (default=hvfhd,dvfhd,hvfsd,dvfsd,hvfxsd,dvfxsd,hvfhigh,dvfhigh,hvfxhigh,dvfxhigh,hvflow,dvflow).
.TP
\fB\-\-url <url>,<url>,...
Record the PIDs contained in the specified iPlayer episode URLs.
.TP
\fB\-\-versions <versions>
Version of programme to record. List is processed from left to right and first version found is downloaded.  Example: '\-\-versions=audiodescribed,default' will prefer audiodescribed programmes if available.
.SS "Output Options:"
.TP
\fB\-\-command, \-c <command>
User command to run after successful recording of programme. Use substitution parameters in command string (see docs for list).
.TP
\fB\-\-command\-radio <command>
User command to run after successful recording of radio programme. Use substitution parameters in command string (see docs for list). Overrides \-\-command.
.TP
\fB\-\-command\-tv <command>
User command to run after successful recording of TV programme. Use substitution parameters in command string (see docs for list). Overrides \-\-command.
.TP
\fB\-\-credits
Download programme credits, if available.
.TP
\fB\-\-credits\-only
Only download programme credits (if available), not programme.
.TP
\fB\-\-file\-prefix <format>
The filename prefix template (excluding dir and extension). Use substitution parameters in template (see docs for list). Default: <name> \- <episode> <pid> <version>
.TP
\fB\-\-limitprefixlength <length>
The maximum length for a file prefix.  Defaults to 240 to allow space within standard 256 limit.
.TP
\fB\-\-metadata
Create metadata info file after recording.
.TP
\fB\-\-metadata\-only
Create specified metadata info file without any recording or streaming.
.TP
\fB\-\-no\-metadata
Do not create metadata info file after recording (overrides \-\-metadata).
.TP
\fB\-\-no\-sanitise
Do not sanitise output file and directory names. Implies \-\-whitespace. Invalid characters for Windows ("*:<>?|) and macOS (:) will be removed.
.TP
\fB\-\-output, \-o <dir>
Recording output directory
.TP
\fB\-\-outputradio <dir>
Output directory for radio recordings (overrides \-\-output)
.TP
\fB\-\-outputtv <dir>
Output directory for tv recordings (overrides \-\-output)
.TP
\fB\-\-raw
Don't remux or change the recording in any way.  Saves output file in native container format (HLS\->MPEG\-TS, DASH\->MP4)
.TP
\fB\-\-subdir, \-s
Save recorded files into subdirectory of output directory.  Default: same name as programme (see \-\-subdir\-format).
.TP
\fB\-\-subdir\-format <format>
The format to be used for subdirectory naming.  Use substitution parameters in format string (see docs for list).
.TP
\fB\-\-suboffset <offset>
Offset the subtitle timestamps by the specified number of milliseconds.  Requires \-\-subtitles.
.TP
\fB\-\-subs\-embed
Embed soft subtitles in MP4 output file. Ignored with \-\-audio\-only and \-\-ffmpeg\-obsolete. Requires \-\-subtitles.
.TP
\fB\-\-subs\-mono
Create monochrome titles, with leading hyphen used to denote change of speaker. Requires \-\-subtitles.
.TP
\fB\-\-subs\-raw
Additionally save the raw subtitles file.  Requires \-\-subtitles.
.TP
\fB\-\-subtitles
Download subtitles into srt/SubRip format if available and supported
.TP
\fB\-\-subtitles\-only
Only download the subtitles, not the programme
.TP
\fB\-\-tag\-only
Only update the programme metadata tag and not download the programme. Use with \-\-history or \-\-tag\-only\-filename.
.TP
\fB\-\-tag\-only\-filename <filename>
Add metadata tags to specified file (ignored unless used with \-\-tag\-only)
.TP
\fB\-\-thumb
Download thumbnail image if available
.TP
\fB\-\-thumb\-ext <ext>
Thumbnail filename extension to use
.TP
\fB\-\-thumbnail\-only
Only download thumbnail image if available, not the programme
.TP
\fB\-\-thumbnail\-series
Force use of series/brand thumbnail (series preferred) instead of episode thumbnail
.TP
\fB\-\-thumbnail\-size <width>
Thumbnail size to use for the current recording and metadata. Specify width: 192,256,384,448,512,640,704,832,960,1280,1920. Invalid values will be mapped to nearest available. Default: 192
.TP
\fB\-\-thumbnail\-square
Download square version of thumbnail image.
.TP
\fB\-\-tracklist
Download track list of music played in programme, if available. Track times and durations may be missing or incorrect.
.TP
\fB\-\-tracklist\-only
Only download track list of music played in programme (if available), not programme.
.TP
\fB\-\-whitespace, \-w
Keep whitespace in file and directory names.  Default behaviour is to replace whitespace with underscores.
.SS "PVR Options:"
.TP
\fB\-\-comment <string>
Adds a comment to a PVR search
.TP
\fB\-\-pvr [pvr search name]
Runs the PVR using all saved PVR searches (intended to be run every hour from cron etc). The list can be limited by adding a regex to the command. Synonyms: \-\-pvrrun, \-\-pvr\-run
.TP
\fB\-\-pvr\-add <search name>
Save the named PVR search with the specified search terms. Search terms required unless \-\-pid specified. Synonyms: \-\-pvradd
.TP
\fB\-\-pvr\-del <search name>
Remove the named search from the PVR searches. Synonyms: \-\-pvrdel
.TP
\fB\-\-pvr\-disable <search name>
Disable (not delete) a named PVR search. Synonyms: \-\-pvrdisable
.TP
\fB\-\-pvr\-enable <search name>
Enable a previously disabled named PVR search. Synonyms: \-\-pvrenable
.TP
\fB\-\-pvr\-exclude <string>
Exclude the PVR searches to run by search name (comma\-separated regex list). Defaults to substring match. Synonyms: \-\-pvrexclude
.TP
\fB\-\-pvr\-list
Show the PVR search list. Synonyms: \-\-pvrlist
.TP
\fB\-\-pvr\-queue
Add currently matched programmes to queue for later one\-off recording using the \-\-pvr option. Search terms required unless \-\-pid specified. Synonyms: \-\-pvrqueue
.TP
\fB\-\-pvr\-scheduler <seconds>
Runs the PVR using all saved PVR searches every <seconds>. Synonyms: \-\-pvrscheduler
.TP
\fB\-\-pvr\-series
Create PVR search for each unique series name in search results. Search terms required. Synonyms: \-\-pvrseries
.TP
\fB\-\-pvr\-single <search name>
Runs a named PVR search. Synonyms: \-\-pvrsingle
.SS "Config Options:"
.TP
\fB\-\-cache\-rebuild
Rebuild cache with full 30\-day programme index. Use \-\-refresh\-limit to restrict cache window.
.TP
\fB\-\-expiry, \-e <secs>
Cache expiry in seconds (default 4hrs)
.TP
\fB\-\-limit\-matches <number>
Limits the number of matching results for any search (and for every PVR search)
.TP
\fB\-\-nopurge
Don't show warning about programmes recorded over 30 days ago
.TP
\fB\-\-prefs\-add
Add/Change specified saved user or preset options
.TP
\fB\-\-prefs\-clear
Remove *ALL* saved user or preset options
.TP
\fB\-\-prefs\-del
Remove specified saved user or preset options
.TP
\fB\-\-prefs\-show
Show saved user or preset options
.TP
\fB\-\-preset, \-z <name>
Use specified user options preset
.TP
\fB\-\-preset\-list
Show all valid presets
.TP
\fB\-\-profile\-dir <dir>
Override the user profile directory
.TP
\fB\-\-refresh, \-\-flush, \-f
Refresh cache
.TP
\fB\-\-refresh\-abortonerror
Abort cache refresh for programme type if data for any channel fails to download.  Use \-\-refresh\-exclude to temporarily skip failing channels.
.TP
\fB\-\-refresh\-exclude <channel>,<channel>,...
Exclude matched channel(s) when refreshing cache (comma\-separated regex list).  Defaults to substring match.  Overrides \-\-refresh\-include\-groups[\-{tv,radio}] status for specified channel(s)
.TP
\fB\-\-refresh\-exclude\-groups <group>,<group>,...
Exclude channel groups when refreshing radio or TV cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-exclude\-groups\-radio <group>,<group>,...
Exclude channel groups when refreshing radio cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-exclude\-groups\-tv <group>,<group>,...
Exclude channel groups when refreshing TV cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-future
Obtain future programme schedule when refreshing cache
.TP
\fB\-\-refresh\-include <channel>,<channel>,...
Include matched channel(s) when refreshing cache (comma\-separated regex list).  Defaults to substring match.  Overrides \-\-refresh\-exclude\-groups[\-{tv,radio}] status for specified channel(s)
.TP
\fB\-\-refresh\-include\-groups <group>,<group>,...
Include channel groups when refreshing radio or TV cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-include\-groups\-radio <group>,<group>,...
Include channel groups when refreshing radio cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-include\-groups\-tv <group>,<group>,...
Include channel groups when refreshing TV cache (comma\-separated values).  Valid values: 'national', 'regional', 'local'
.TP
\fB\-\-refresh\-limit <days>
Minimum number of days of programmes to cache.  Makes cache updates slow.  Default: 7 Min: 1 Max: 30
.TP
\fB\-\-refresh\-limit\-radio <days>
Number of days of radio programmes to cache.  Makes cache updates slow.  Default: 7 Min: 1 Max: 30
.TP
\fB\-\-refresh\-limit\-tv <days>
Number of days of TV programmes to cache.  Makes cache updates slow.  Default: 7 Min: 1 Max: 30
.TP
\fB\-\-skipdeleted
Skip the download of metadata/thumbs/subs if the media file no longer exists.  Use with \-\-history & \-\-metadataonly/subsonly/thumbonly.
.TP
\fB\-\-webrequest <urlencoded string>
Specify all options as a urlencoded string of "name=val&name=val&..."
.SS "External Program Options:"
.TP
\fB\-\-atomicparsley <path>
Location of AtomicParsley binary
.TP
\fB\-\-ffmpeg <path>
Location of ffmpeg binary. Assumed to be ffmpeg 3.0 or higher unless \-\-ffmpeg\-obsolete is specified.
.TP
\fB\-\-ffmpeg\-force
Bypass version checks and assume ffmpeg is version 3.0 or higher
.TP
\fB\-\-ffmpeg\-loglevel <level>
Set logging level for ffmpeg. Overridden by \-\-quiet and \-\-silent. Default: 'fatal'
.TP
\fB\-\-ffmpeg\-obsolete
Indicates you are using an obsolete version of ffmpeg (<1.0) that may not support certain options. Without this option, MP4 conversion may fail with obsolete versions of ffmpeg.
.SS "Tagging Options:"
.TP
\fB\-\-no\-artwork
Do not embed thumbnail image in output file. Also removes existing artwork. All other metadata values will be written.
.TP
\fB\-\-no\-tag
Do not tag downloaded programmes.
.TP
\fB\-\-tag\-credits
Add programme credits (if available) to lyrics field.
.TP
\fB\-\-tag\-format\-show
Format template for programme name in tag metadata. Use substitution parameters in template (see docs for list). Default: <name>
.TP
\fB\-\-tag\-format\-title
Format template for episode title in tag metadata. Use substitution parameters in template (see docs for list). Default: <episodeshort>
.TP
\fB\-\-tag\-isodate
Use ISO8601 dates (YYYY\-MM\-DD) in album/show names and track titles
.TP
\fB\-\-tag\-podcast
Tag downloaded radio and tv programmes as iTunes podcasts
.TP
\fB\-\-tag\-podcast\-radio
Tag only downloaded radio programmes as iTunes podcasts
.TP
\fB\-\-tag\-podcast\-tv
Tag only downloaded tv programmes as iTunes podcasts
.TP
\fB\-\-tag\-tracklist
Add track list of music played in programme (if available) to lyrics field.
.TP
\fB\-\-tag\-utf8
Use UTF\-8 encoding for non\-ASCII characters in AtomicParsley parameter values (Linux/Unix/macOS only). Use only if auto\-detect fails.
.SS "Misc Options:"
.TP
\fB\-\-encoding\-console\-in <name>
Character encoding for standard input (currently unused).  Encoding name must be known to Perl Encode module.  Default (only if auto\-detect fails): Linux/Unix/OSX = UTF\-8, Windows = cp850
.TP
\fB\-\-encoding\-console\-out <name>
Character encoding used to encode search results and other output.  Encoding name must be known to Perl Encode module.  Default (only if auto\-detect fails): Linux/Unix/OSX = UTF\-8, Windows = cp850
.TP
\fB\-\-encoding\-locale <name>
Character encoding used to decode command\-line arguments.  Encoding name must be known to Perl Encode module.  Default (only if auto\-detect fails): Linux/Unix/OSX = UTF\-8, Windows = cp1252
.TP
\fB\-\-encoding\-locale\-fs <name>
Character encoding used to encode file and directory names.  Encoding name must be known to Perl Encode module.  Default (only if auto\-detect fails): Linux/Unix/OSX = UTF\-8, Windows = cp1252
.TP
\fB\-\-index\-maxconn <number>
Maximum number of connections to use for concurrent programme indexing.  Default: 5 Min: 1 Max: 10
.TP
\fB\-\-purge\-files
Delete downloaded programmes more than 30 days old
.TP
\fB\-\-throttle <Mb/s>
Bandwidth limit (in Mb/s) for media file download. Default: unlimited. Synonym: \-\-bw
.TP
\fB\-\-trim\-history <# days to retain>
Remove download history entries older than number of days specified in option value.  Cannot specify 0 \- use 'all' to completely delete download history
.SS "Deprecated Options:"
.TP
\fB\-\-no\-index\-concurrent
Do not use concurrent indexing to update programme cache.  Cache updates will be very slow.
.SH AUTHOR
get_iplayer was written by Phil Lewis <iplayer2 (at sign) linuxcentre.net> and is now maintained by the contributors at https://github.com/get\-iplayer/get_iplayer
.PP
This manual page was originally written by Jonathan Wiltshire <jmw@debian.org> for the Debian project (but may be used by others).
.SH COPYRIGHT NOTICE
get_iplayer v3.20, Copyright (C) 2008\-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use \-\-warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use \-\-conditions for details.



